/* Modulo 27  - Definindo base  e primeira requisição */

export const LOGIN_USER = 'LOGIN_USER',
	LOGOUT_USER = 'LOGOUT_USER',
	GET_PEDIDOS = 'GET_PEDIDOS',
	GET_PEDIDO = 'GET_PEDIDO',
	CANCELAR_PEDIDO = 'CANCELAR_PEDIDO',
	LIMPAR_PEDIDO = 'LIMPAR_PEDIDO',
	GET_CLIENTES = 'GET_CLIENTES';